import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ScreenProvider } from "@/lib/ScreenProvider";
import Header from "@/components/Header";
import { LogIn } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isAuthenticated = false;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row  max-w-[1500] ">
        {!isAuthenticated ? (
          <LogIn />
        ) : (
          <ScreenProvider>
            <Sidebar />
            <div className="flex-1 ">
              <Header />
              {children}
            </div>
          </ScreenProvider>
        )}
      </body>
    </html>
  );
}
